# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-03 06:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_count', models.IntegerField()),
                ('url', models.URLField()),
                ('date', models.DateTimeField(verbose_name='date harvested')),
            ],
        ),
        migrations.CreateModel(
            name='Wines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('color', models.CharField(max_length=50)),
                ('eyes', models.TextField()),
                ('nose', models.TextField()),
                ('mouth', models.TextField()),
                ('overall', models.TextField()),
                ('producer', models.TextField()),
                ('region', models.CharField(max_length=150)),
                ('sub_region', models.CharField(max_length=150)),
                ('variety', models.CharField(max_length=150)),
                ('vintage', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('harvest_data', models.TextField()),
                ('harvested_date', models.DateTimeField(verbose_name='date harvested')),
                ('harvested_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wine_db.History')),
            ],
        ),
    ]
