# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='abv',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='wines',
            name='color',
            field=models.CharField(default='N/A', max_length=50),
        ),
        migrations.AlterField(
            model_name='wines',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wines',
            name='region',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='wines',
            name='sub_region',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='wines',
            name='variety',
            field=models.CharField(default='N/A', max_length=150),
        ),
        migrations.AlterField(
            model_name='wines',
            name='vintage',
            field=models.CharField(default='N/A', max_length=150),
        ),
    ]
