# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 05:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_db', '0002_auto_20151207_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='wines',
            name='tags',
            field=models.CharField(default='', max_length=300),
        ),
    ]
