# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-08 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wine_db', '0003_wines_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wines',
            name='price',
            field=models.CharField(default=0, max_length=150),
        ),
    ]
